name: Auto Update PR Description

on:
  pull_request:
    types: [opened]

jobs:
  update-pr-description:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read PR description content
        id: read_description
        run: |
          $content = Get-Content ".github\pr-comment.md" -Raw
          $content | Out-File -FilePath description.txt -Encoding utf8NoBOM
          echo "DESCRIPTION_CONTENT<<EOF" >> $env:GITHUB_ENV
          Get-Content description.txt | ForEach-Object { echo $_ >> $env:GITHUB_ENV }
          echo "EOF" >> $env:GITHUB_ENV

      - name: Update PR body
        run: |
          $headers = @{
            Authorization = "Bearer ${{ secrets.MY_PAT }}"
            Accept = "application/vnd.github+json"
          }

          $bodyContent = Get-Content "description.txt" -Raw
          $jsonBody = @{ body = $bodyContent } | ConvertTo-Json -Compress

          $prNumber = "${{ github.event.pull_request.number }}"
          $repo = "${{ github.repository }}"
          $url = "https://api.github.com/repos/$repo/pulls/$prNumber"

          Invoke-RestMethod -Uri $url -Method Patch -Headers $headers -Body $jsonBody
