name: Comment on Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  comment:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read comment content
        id: read_comment
        run: |
          $content = Get-Content .github\pr-comment.md -Raw
          $content = $content -replace "`r", ""  # loại bỏ CRLF nếu có
          Add-Content -Path $env:GITHUB_OUTPUT -Value "content<<EOF"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "$content"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "EOF"

      - name: Create PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.MY_PAT }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.read_comment.outputs.content }}
